# vim: set ts=2 sts=2 sw=2 noet :
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ 
			(modulesPath + "/profiles/qemu-guest.nix")
    ];

	boot.initrd.availableKernelModules = [ "ata_piix" "floppy" "sd_mod" "sr_mod" ];
	boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
		{ 
			device = "/dev/disk/by-uuid/04ac3477-14e6-4a28-be38-498a332e22ab";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { 
			device = "/dev/disk/by-uuid/3d2a3f72-a274-42f5-b04d-ce785b416457";
      fsType = "ext2";
    };

  swapDevices = [ ];

}
